name: Fedora Rawhide

on: [push]

jobs:
  fedora_rawhide:
      name: gcc
      runs-on: ubuntu-latest
      container:
        image: fedora:rawhide
      steps:
        - uses: actions/checkout@master
        - name: gcc10 static analyzer
          run: |
            dnf install -y which autoconf automake
            dnf -y groupinstall "Development Tools"
            ./bootstrap
            export CFLAGS="-fanalyzer"
            ./configure
            make
