name: Fedora Rawhide

on: [push]

jobs:
  fedora_rawhide:
      name: gcc
      runs-on: ubuntu-latest
      container:
        image: fedora:rawhide
      steps:
        - uses: actions/checkout@master
        - name: install prerequisites
          run: |
            dnf install -y which autoconf automake libtool openssl-devel pam-devel libX11-devel libXfixes-devel
            dnf -y groupinstall "Development Tools"
        - name: configure
          run: |
            ./bootstrap
            export CFLAGS="-fanalyzer"
            ./configure
        - name: gcc10 static analyzer
          run: |
            make

